name: Update Timestamp

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current timestamp
      run: echo "$(date)" > timestamp

    - name: Configure git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add timestamp
        git commit -m "Update timestamp"
        git push
