name: Update Timestamp

on:
  schedule:
    - cron: "*/59 * * * *"
  workflow_dispatch:

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false # Use personal token instead of GITHUB_TOKEN
        fetch-depth: 0             # Ensure full history is fetched

    - name: Setup GPG
      run: |
        echo "${{ secrets.GPG }}" | gpg --batch --import
        echo "trust\n5\ny\n" | gpg --command-fd 0 --batch --edit-key ${{ secrets.REPO_OWNER_EMAIL }} trust

    - name: Setup Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ secrets.REPO_OWNER_EMAIL }}"
        git config --global user.signingkey $(gpg --list-keys --with-colons | grep '^pub' | head -n 1 | cut -d':' -f5)
        git config --global commit.gpgsign true

    - name: Get current timestamp
      run: echo "$(date)" > timestamp

    - name: Commit and Push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git add timestamp
        git commit -m "Update timestamp"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
        git pull --rebase origin main # Pull latest changes before pushing
        git push origin main
